# STAGE 1 · 2층 방 — 4 구간 연결형 스테이지 **Stage Construction Guideline**

> 작성 2026-08-30 · Claude · 지시자 도형
> 이 문서는 **제작 지침**이다. 아직 씬을 만들지 않았다.
> "STEP 1-1 제작 시작" 이라고 지시하면 이 문서의 §STEP 4 를 그대로 짓는다.
>
> ★모든 수치는 **실제로 재서** 넣었다. 못 잰 것은 `[확인 필요]` 로 표시했고 추측으로 채우지 않았다.

---

## 0. 이번 설계가 v4 와 무엇이 다른가 (도형님 지시 반영)

| | v4 (현재 저장소) | **v5 (이 문서)** |
|---|---|---|
| 배경 | room.png 를 **두 조각으로 잘라** 배율 1.15 로 깔고 사이를 벽으로 끊음 | **원화 한 장을 통째로 배율 2.90 으로 늘림** |
| 방 크기 | 2955 × 1062 | **6192 × 2678** |
| 방 높이 ÷ 플레이어 키 | 11.1 배 | **27.9 배** |
| 구간 수 | 2 (1-1 / 1-2) | **4 (1-1 ~ 1-4)** |
| 공중 발판 | **못 쓴다** (층고 1062 에 안 들어감) | **쓸 수 있다** (층고 2678 = 겹치는 두 층 사이 352 가 4.7 층 들어감) |
| 캐릭터 체감 | 사람 | **쥐** |

도형님 지시: *"노란 박스 안에 있는 것들이 전부 한 배경에 스테이지로 쪼개서 만들거야.
배경을 엄청 크게 하고 캐릭터가 완전 쥐가 돌아다니는 것처럼 하는거지."*

★ 이 지시는 메모리의 **배경 규칙**("이어 붙이지 않는다 · 반전하지 않는다 · 원화 한 장을 크게 늘린다")과
**정확히 일치**한다. v4 가 배율을 1.15 로 낮춘 이유는 "캐릭터가 너무 작아 보인다" 였는데,
지금은 **작아 보이는 것이 목표**다. 그래서 v3 이 쓰던 배율대(2.9)로 돌아간다.

⚠ 대신 v4 의 구역 분할(가운데 벽 500)은 **버린다.** 한 장을 통째로 쓰면 자를 이유가 없다.
구간은 벽이 아니라 **카메라 공간 + 높이 층**으로 나눈다.

### 가이드 이미지 읽기 — 왜 이 배치가 맞는가

가이드의 노란 박스 4 개는 room.png 의 **네 사분면**이다. 근거:

- 박스 2(우상)와 박스 4(우하)에만 **창문이 보인다.** 창은 원화 py 310…769 로
  세로 중앙선(py 600)을 **가로지른다** → 오른쪽 위·아래 두 칸에 모두 걸린다. ✔
- 박스 1(좌상)·3(좌하)은 어둡다 = 원화 왼쪽 절반(책상·책장·옷장)에는 광원이 없다. ✔
- 라벨도 맞는다 — 1-2 "창가", 1-3 "책장을 넘어감"(책장은 원화 왼쪽), 1-4 "1층으로 떨어지는 곳".

**→ 4 구간은 한 방 안의 네 사분면이고, 동선은 ┏ 자 나선이다.**

```
   ┌─────────────────┬─────────────────┐
   │ 1-1  지그재그    │→ 1-2  창가       │   윗층 (y −1900 … −2570)
   │ 좌상             │   우상  ┐        │
   ├─────────────────┼────────┼────────┤
   │ 1-3  가구 밑     │←───────┘        │   중·아래층 (y −1191 … 0)
   │ 좌하   └────────→│ 1-4  침대·낙하   │
   └─────────────────┴─────────────────┘
```

---

# STEP 1 — Current Project Analysis (실제로 확인한 것)

## 1.1 실행 흐름 / 씬 구조

```
project.godot  run/main_scene = res://scenes/lobby/lobby.tscn
   └ lobby.gd  →  챕터.씬경로(1)  →  scenes/집/스테이지_1_2층방.tscn
```

- **순서의 유일한 출처는 `scripts/스마트월드/챕터.gd` 의 `스테이지표`** 다. 씬 파일에는 순서 정보가 없다.
- 표에는 이미 4 줄이 있다 — 1 · 2층 방 / 2 · 2층 복도·계단 / 3 · 1층 거실 / 4 · 1층 주방.
  **이번 4 구간은 그 표의 1 번 한 줄 안에서 벌어진다.** 표는 손대지 않는다.
- 현재 STAGE 1 씬: `scenes/집/스테이지_1_2층방.tscn` (988 줄) · 빌더 `tools/build_스테이지_1_2층방.gd` (792 줄)
- **Main Scene 이라는 노드는 없다.** 스테이지 루트가 곧 매니저다 (`월드.gd` = `class_name 스마트월드`).

## 1.2 스테이지 루트 (`scripts/스마트월드/월드.gd`) — 이것이 곧 Main

`Node2D` + `월드.gd`. 스테이지 하나를 통째로 굴린다.

| @export | 기본값 | 뜻 |
|---|---|---|
| `스테이지_이름` | | HUD·일시정지 메뉴 표기 |
| `카메라_리밋` | Rect2() | 비우면 리밋 없음 |
| `카메라_줌` | 0.85 | ProtoCamera 기본 줌 |
| `시작_위치` | (200,0) | 사망 시 복귀 지점 |
| `낙사_y` | 1800 | 최후 안전장치 |
| `치명_낙하거리` | 520 | **한 번에 이만큼 떨어지면 즉사** |
| `안전지점_자동저장` | true | 마지막으로 안전하게 서 있던 땅을 자동 체크포인트로 |
| `안전지점_유예` | 0.45 | 그 땅에서 이만큼 버텨야 인정 |
| `몸통_접촉_사망` | true | |

`_ready()` 가 하는 일: 플레이어 몸 실측 → 진입 위치 결정(통로 우선) → **ProtoCamera 부착
(Player.tscn 안의 Camera2D 는 끈다)** → 음향·등장 연출 → **페인트총 부착** → 낙하 감시 → HUD → 메뉴.

★ `process_physics_priority = 10` — 플레이어보다 **뒤에** 돈다. 색 강제를 같은 프레임에 되돌리기 위해서다.

## 1.3 Player (`scenes/player/Player.tscn` + `scripts/player.gd`)

```
Player (CharacterBody2D · scale 0.795 × 0.368 · floor_snap_length 32)
├ CharacterSprite (AnimatedSprite2D) └ 색겹침 (AnimatedSprite2D)
├ GunRig (Node2D · 부모 비균등 스케일 상쇄) └ Gun (gun.gd) └ Muzzle (Marker2D)
├ ActionFX · Camera2D(월드가 끈다)
└ CollisionPolygon2D   ← 6점 폴리곤. 월드 실측 44 × 95.63
```

- `player.gd` 는 **이동·점프·색 상태만** 담당. 사격·사망 판정은 없다.
- 점프는 `타일_크기 / 점프_높이_칸 / 점프_거리_칸 / move_speed` 에서 **역산**된다 (`_점프_재계산()`).
- 씬 인스턴스 오버라이드: `점프_높이_칸 = 10` · `점프_거리_칸 = 10`.
  **집 챕터는 빌더가 `점프_거리_칸 = 15` 로 덮어쓴다** (`const 튜닝`). 설계에 쓸 숫자는 후자다.

### ★★ 설계에 결정적인 두 줄 (실제 코드에서 확인)

```gdscript
# player.gd _physics_process()
var dir := Input.get_axis("move_left", "move_right")
velocity.x = dir * move_speed          # ← 매 물리 프레임 x 를 통째로 덮어쓴다
```

> **수평 넉백을 `velocity.x` 로 주면 다음 프레임에 지워진다.**
> 반대로 `velocity.y` 는 중력이 누적될 뿐 덮어쓰이지 않는다 → **수직 개입은 안전하다.**
> → 이것이 §STEP 9 의 기믹 구현 방식을 통째로 결정한다.

## 1.4 총 / 총알 — **두 벌이 있다. 스마트월드가 쓰는 것은 뒤쪽이다**

| | 구 시스템 | **스마트월드 시스템 (이번에 쓸 것)** |
|---|---|---|
| 총 | `scripts/gun.gd` (Player 자식 Gun) | `scripts/스마트월드/총.gd` (`class_name 페인트총`) |
| 총알 | `scripts/bullet.gd` + `scenes/bullet/Bullet.tscn` | `scripts/스마트월드/총알.gd` (`class_name 페인트총알`) |
| 부착 | Player.tscn 에 박혀 있음 | **`월드.gd` 가 런타임에 붙이고 구 Gun 의 `_process` 를 끈다** |
| 물리 | 직선 | **포물선(중력 900) + 송풍기 바람 영향** |
| 명중 판정 | `body_entered` | **매 프레임 레이캐스트** (레이어 `1 \| 8`) + Area 겹침 (`16 \| 32`) |

### ★ 명중 계약 (파괴 가능 바닥이 여기 올라탄다)

```
총알 → _칠할대상_찾기(맞은것)      # 콜리전 바디에서 부모로 거슬러 올라가며 has_method("명중") 찾기
     → 페인트코어.명중_처리(대상, 색, 지점)
     → 대상.명중(색: int, 월드좌표: Vector2) -> String
        반환값: "painted" | "progress" | "wasted" | "blocked" | "mixed_gray"
```

**총·총알을 새로 만들 필요가 전혀 없다.** `명중()` 을 가진 노드를 놓기만 하면 맞는다.

## 1.5 SmartShape2D 구조 — ★기존 방식을 그대로 쓴다

- 애드온 `addons/rmsmartshape` v3.3.1, 에디터 플러그인 활성.
- 지형 스크립트 `scripts/스마트월드/지형.gd` = `class_name 스마트지형 extends SS2D_Shape_Closed`.
  주요 `@export`: `칠하기_허용` · `무색일때_통과` · `필요횟수_수동` · `시작상태` · `위치별_판정`.
- **확정 키트 12 종** (`scenes/집/스마트 매쉬 assets/`):

| 폴더 | Template | 콜리전 대 그림 오차 | 이번에 쓰나 |
|---|---|---|---|
| BRICK_벽돌 | `벽돌 테스` / `벽돌 계단` (±흰색) | **0.0 ~ +2.0 px** ✔ | **구조 전부** |
| WOOD_나무 | `TEMPLATE_WOOD_SOLID` / `_STAIRS` (±흰색) | **0.0 px** ✔ | **가구·발판 전부** |
| GRASS_잔디 | 4 종 | **+44.8 px 사방** ✘ | **안 쓴다** (밟는 면 금지) |

⚠ `벽돌 테스` · `벽돌 테스_흰색` 만 루트가 SS2D 가 아니다 (루트 Node2D → 자식 `SS2D_Shape_Closed`).
→ 빌더의 `_모양노드()` 가 껍데기를 벗긴다. **이 함수를 그대로 재사용한다.**

### 빌더가 지형을 만드는 방식 (그대로 답습한다)

```
Template 인스턴스 → 껍데기 벗기기 → 이름/position/칠하기_허용 설정
→ SS2D_Point_Array 에 로컬 점 넣고 close_shape()
→ SS2D_CollisionGen 으로 콜리전 폴리곤 직접 구워서 StaticBody2D/CollisionPolygon2D 에 꽂기
```
**재질·texture_scale·코너·collision_size 는 Template 이 갖고 있으므로 절대 손대지 않는다.**

## 1.6 TileSet

`assets/tileset/`·`assets/tilesets/` 에 남아 있으나 **집 4 스테이지는 TileMapLayer 를 하나도 안 쓴다.**
`terrain_tileset.tres` 는 로비 디오라마 전용. → **이번 작업에서 TileSet 은 건드리지 않는다.**

## 1.7 Collision Layer / Mask — 현재 규약 (전수 조사 결과)

| 비트 | 레이어 번호 | 쓰는 것 | 근거 파일 |
|---|---|---|---|
| **1** | 1 | 플레이어(기본값) · 밟을 수 있는 지형(SS2D StaticBody2D) · 통과플랫폼 · 도약대 `발판` · 연결통로 바디 · 송풍기 본체 · 식물A · 물저장고 | `연결통로.gd:156`, `도약대.gd:91`, `통과플랫폼.gd:33` |
| **8** | 4 | **무색 유령 지형** (`무색일때_통과`) · 투명블럭 — 플레이어는 통과, 총알은 맞는다 | `지형.gd:유령_레이어비트`, `투명블럭.tscn` |
| **16** | 5 | 색칠 가능한 통과형 오브젝트 (식물 B 덤불) | `식물_b.gd:41` |
| **32** | 6 | 유체(물·연기) | `유체.tscn:7` |
| **0 / mask 1** | — | **감지 전용 Area2D** (도약대 판정 · 가시 · 색레이저 · 빛기둥 · 연결통로 · 카메라공간) | 7 개 파일 공통 |
| **0 / mask 16\|32** | — | 총알 (단단한 지형은 레이캐스트 `1\|8` 로 따로 본다) | `총알.gd:47` |

> ★ **새 레이어가 필요 없다.** 이번 기믹 7 종은 전부 `layer 0 / mask 1` 감지 Area2D 이거나
> `layer 1` 단단한 바디다. 기존 규약 안에서 전부 표현된다. (§STEP 9 표 참고)

## 1.8 Camera2D

- `scripts/proto/proto_camera.gd` (`class_name ProtoCamera`) — 월드가 만들어 붙인다.
  `setup(플레이어)` · `set_region_zoom(줌, 즉시)` · `set_limit_rect(Rect2, 즉시)` · `add_trauma()`
- `scripts/proto/카메라_공간.gd` — **Area2D. 들어가면 그 구역의 줌으로 바뀐다.**
  `@export 크기: Vector2` · `줌_배수: float` · `틈새빛_사용: bool`
  ⚠ **`틈새빛_사용` 은 반드시 `false`.** 기본 true 면 화면에 "빛 쏘는 구슬" 6 줄기가 그려진다
  (2026-08-29 에 원인 규명에 반나절 걸린 그것).

## 1.9 사용 가능한 기존 Gimmick — ★새로 만들 것이 생각보다 적다

| 필요한 것 | 이미 있는가 | 파일 | 그대로 쓸 수 있나 |
|---|---|---|---|
| **트램폴린** | ✅ **있다** | `scripts/스마트월드/도약대.gd` (`class_name 도약대`) | **그대로 쓴다.** Area2D 가 `p.velocity.y = 도약속도` 로 직접 쓴다 |
| 움직이는 서랍 | ✅ 있다 | `scripts/장애물/움직이는발판.gd` (AnimatableBody2D) | `이동거리`·`이동방향`·`왕복시간`·`시작지연` — 서랍에 그대로 맞는다 |
| 가시 | ⚠ 있으나 **안 죽는다** | `scenes/장애물/가시.tscn` | §1.11 참고 — `월드.gd` 4 줄 추가 필요 |
| 통과 발판(한 방향) | ✅ 있다 | `scripts/스마트월드/통과플랫폼.gd` | 계단 OneWay 용 |
| 무너지는 발판 | ✅ 있다 | `scripts/장애물/무너지는발판.gd` | 예비 |
| 창문·커튼·빛 | ✅ 있다 | `창문커튼.gd` · `빛기둥.gd` (모드 연출/경계/발판) | 연출·색경계는 되지만 **넉백은 없다** |
| 바람 | ⚠ **총알만 민다** | `송풍기.gd` | **플레이어를 밀지 않는다** — 새 스크립트 필요 |
| 빛 넉백 | ❌ 없다 | — | **새 스크립트 필요** |
| 굴러오는 연필 | ❌ 없다 | — | **새 스크립트 필요** (`떨어지는블록.gd` 를 참고) |
| 파괴 가능 바닥 | ❌ 없다 | — | **새 스크립트 필요** — 단, `명중()` 계약만 지키면 총 시스템은 무수정 |
| 체크포인트 | ⚠ 있으나 **연결 안 됨** | `scenes/장애물/체크포인트.tscn` | §1.11 참고 |

## 1.10 색 규칙 (2026-08-30 변경 — 설계에 직결된다)

`scripts/스마트월드/색규칙.gd`: **"안 칠한 것은 무색이 아니라 검정이다."**

- 흰색 플레이어는 안 칠한 나무·벽돌 위에서 **즉사**한다. 회색만 누구에게나 안전.
- `칠하기_허용 = false` 인 것(벽·천장 같은 구조물)은 **색 규칙 밖** — 절대 안 죽인다.

> ★ **이번 스테이지의 결정**: STAGE 1 은 색 퍼즐을 하지 않는다 (색 퍼즐은 STAGE 3 부터).
> → **지형은 전부 `칠하기_허용 = false`.** 단 하나의 예외가 `파괴가능바닥`(1-4)이다.
> 이렇게 하면 플레이어가 실수로 Shift 를 눌러도 죽지 않고, 총을 쏴서 자기 발밑을
> 검게 칠해 흰색으로 갇히는 사고도 원천 봉쇄된다.
> 부수적 이득 — **칠할 수 있는 지형이 딱 하나뿐이라 "어디를 쏘라"가 저절로 읽힌다.**

## 1.11 ★★ 확인된 구멍 2 개 — 제작 전에 도형님 결정이 필요하다

### (A) `월드.gd` 는 `hazard` 그룹을 **보지 않는다**

```
가시.gd:34   add_to_group("hazard")   # 주석: "stage_lab 이 이 그룹만 보고 사망 판정을 한다"
grep hazard → scripts/proto/stage_lab.gd:352 에만 있다
scripts/스마트월드/월드.gd 의 _사망_판정() 에는 hazard 가 없다
```

→ **가시·회전톱·떨어지는블록을 지금 스테이지에 놓으면 그림만 나오고 안 죽는다.**
   1-1 의 Brick Spike Trap 과 1-3 의 연필(즉사 옵션)이 여기 걸린다.

**제안하는 최소 수정** (`월드.gd::_사망_판정()` 맨 앞에 4 줄):

```gdscript
	# ★[2026-08-31] hazard 그룹 — 색과 무관한 즉사 함정(가시·톱·구르는 물체).
	#   지금까지 이 판정은 구 매니저(stage_lab.gd)에만 있었다. 스마트월드로 옮겨온
	#   스테이지에서는 가시를 놔도 그림만 나오고 안 죽었다.
	#   ⚠ 색 규칙과 무관하다 — 여기서 색을 보면 "칠하면 안전한 가시"가 되어 규칙이 흐려진다.
	for n in get_tree().get_nodes_in_group("hazard"):
		var a := n as Area2D
		if a and a.monitoring and a.get_overlapping_bodies().has(_플레이어):
			return true
```

- 수정 범위: **`월드.gd` 한 함수에 4 줄 추가.** 기존 동작은 하나도 안 바뀐다
  (지금까지 스마트월드 스테이지에 hazard 그룹 노드가 **하나도 없었다** — 회귀 위험 0).
- `player.gd` · `gun.gd` · `bullet.gd` · SS2D · TileSet · Material · Camera 는 **손대지 않는다.**

### (B) `체크포인트.tscn` 도 `월드.gd` 와 연결되어 있지 않다

`체크포인트.gd` 는 `checkpoint` 그룹을 쓰고 `stage_lab.gd:362` 만 연결한다.

→ **제안: 이번엔 체크포인트 씬을 쓰지 않는다.** `월드.gd` 의 `안전지점_자동저장`(기본 켜짐)이
   "마지막으로 0.45 초 이상 안전하게 서 있던 땅"을 자동으로 기억하므로, 4 구간짜리
   긴 스테이지에서도 처음으로 되돌아가지 않는다. **코드 수정 0.**
   구간 시작점을 명시적으로 고정하고 싶어지면 그때 (A)와 같은 방식으로 4 줄을 더 붙인다.

---

# STEP 2 — Player Capability (실측값)

`Godot --headless --path . -s res://tools/측정_플레이어_능력.gd -- --거리칸 15` 를 **실제로 돌린 결과**
(2026-08-30 · 집 챕터 세팅):

| 항목 | 값 | 설계에 쓰는 법 |
|---|---|---|
| PLAYER_COLLISION_WIDTH | **44.00** | 통로 최소 폭 |
| PLAYER_COLLISION_HEIGHT | **95.63** | 통로 최소 높이의 뼈대 |
| 몸_중심오프셋_y | −48.18 | 원점 = 발바닥 |
| MOVE_SPEED | 390.00 | |
| JUMP_VELOCITY | **−855.66** | |
| GRAVITY | **2287.97** | 상승_배수 1.0 |
| 물리틱 | 60 | |
| MAX_JUMP_HEIGHT | **167.24** | |
| 체공시간 | **0.63 초** | 바람의 체공 연장 기준값 |
| MAX_HORIZONTAL_JUMP_DISTANCE | 256.81 | |
| **SAFE_HORIZONTAL_JUMP_DISTANCE** | **218.29** | |
| MAX_CLIMBABLE_STEP_HEIGHT | 160.28 | |
| **SAFE_STEP_HEIGHT** | **128.22** | |
| MIN_CORRIDOR_HEIGHT | 96.09 | |
| MIN_HOLE_WIDTH | 46.00 | |
| **SAFE_DROP_HEIGHT** | **390.00** | |
| **MAX_SAFE_DROP_HEIGHT** | **520.00** | 이 이상 한 번에 떨어지면 즉사 |

카메라: `카메라_줌` 은 스테이지가 정한다 (v4=1.55). **이번엔 1.00** (§STEP 3).

---

# STEP 3 — Global Stage Guideline

## 3.1 좌표계 — ★배율 상수 하나가 전부를 결정한다

```
const 배율 := 2.90                        # 이 상수만 고치면 방·배경·지형이 같이 움직인다
world_x = 원화x         × 배율
world_y = (원화py − 950) × 배율            # 원화 바닥선 py 950 → world y 0
```

| | 값 |
|---|---|
| 원화 | `assets/background/room.png` **2135 × 1200** |
| 방 | x **0 … 6191.5** · y **−2678 … 0** (층고 2678) |
| 층고 ÷ 플레이어 키 | **27.9 배** ← "쥐" |
| 바닥/천장 구조 두께 | 300 |
| 바깥 벽 두께 | 500 |
| 카메라 리밋 | `Rect2(−600, −3078, 7392, 3678)` |
| 카메라 기본 줌 | **1.00** → 보이는 영역 1920 × 1080 = 방의 가로 31 % · 세로 40 % |
| 원화 밝기 | **1.05** (v3 이 실제로 찍어 보고 고친 값. 확대하면 밝은 조각이 화면을 회색으로 띄운다) |
| 벽 시차 | 0.98 |
| 앞바닥 띠 | 원화 py 962 … 1075 |

## 3.2 원화 실측 좌표 — ★`tools/측정_원화_명도지도.gd` 로 잰 것 (이번에 새로 만든 도구)

```bash
Godot --headless --path . -s res://tools/측정_원화_명도지도.gd -- res://assets/background/room.png 54 34 0 0 1067 1200
Godot --headless --path . -s res://tools/측정_원화_명도지도.gd -- res://assets/background/room.png 54 34 1067 0 1068 1200
```
(⚠ 원화가 어두워 통째로 보면 창문 하나가 정규화를 독식한다 → 좌·우 반씩 나눠 본다)

| 요소 | 원화 x | 원화 py(윗면) | **world x** | **world y(윗면)** | 신뢰도 |
|---|---|---|---|---|---|
| 천장선 | 전체 | 26.7 | | **−2678** | 기존 빌더 상수 ✔ |
| 천장 들보 아랫면 | 전체 | ≈250 | | ≈−2030 | 명도 단차로 확인 |
| 책상·의자(좌) | 0 … 260 | ≈780 | 0 … 754 | ≈−493 | 명도지도 |
| **책장** | 257 … 455 | ≈280 | 745 … 1320 | **≈−1943** | 명도지도 |
| **옷장** | 514 … 790 | ≈282 | 1491 … 2291 | **≈−1937** | 명도지도 + 기존 상수(오른끝 779) |
| 궤짝 | 790 … 900 | ≈860 | 2291 … 2610 | ≈−261 | 명도지도 |
| **침대** | 806 … 1356 | 헤드보드 ≈683 / 매트리스 ≈843 | 2337 … 3932 | **헤드보드 −774 / 매트리스 −310** | 기존 상수 + 명도지도 |
| **빈 벽 (설계 여지)** | 1067 … 1380 | 200 … 800 | **3094 … 4002** | −2175 … −435 | 명도지도에서 균일 |
| 커튼(좌) | 1482 … 1581 | ≈300 | 4298 … 4585 | ≈−1885 | 명도지도 |
| **창틀 전체** | **1591 … 1911** | **310 … 769** | **4614 … 5542** | **−1856 … −525** | 기존 상수 ✔ 명도지도와 일치 |
| 창 유리(가장 밝은 면) | 1601 … 1838 | 370 … 740 | 4643 … 5330 | −1682 … −609 | 명도지도 |
| 창 가로살 | | ≈539 | | **≈−1191** | 창틀 중앙 |
| 커튼(우) | 1858 … 1900 | ≈300 | 5388 … 5510 | ≈−1885 | 명도지도 |
| 의자·탁자(우) | 1708 … 2135 | ≈780 | 4953 … 6192 | ≈−493 | 기존 상수 |
| **바닥선** | 전체 | **950** | | **0** | 기존 상수 ✔ py 952 에 명도 단차 |

`[확인 필요]` 가구의 **세로** 좌표(≈ 붙은 것)는 명도 격자 35 px 해상도로 읽은 값이다.
제작 착수 시 `tools/원화_잘라보기.gd` 로 해당 구간만 확대해 ±10 px 안으로 확정한다.

## 3.3 게임플레이 절대 치수 — **배율과 무관하다** (플레이어가 안 바뀌니까)

| 항목 | 설계값 | 실측 한계 | 레벨검사 강제선 |
|---|---|---|---|
| 상승(한 칸) | **≤ 110** | 160.28 | 세로 128 |
| 뛰어 건널 틈 | **≤ 150** | 256.81 | 가로 204 |
| 단차 | **≤ 110** | 128.22 | |
| 계단 한 단 폭 | **≥ 300** | — | 코너 쿼드가 사방 90 을 먹는다 |
| 설계 낙차 | **≤ 330** | 안전 390 / 즉사 520 | |
| 통로 높이 | **≥ 170** | 실효 = 170 − 48 = 122 > 96 ✔ | |
| 도형 최소 폭 | **≥ 300** | | |
| 공중 발판 두께 | **≥ 160** | 얇으면 엣지 띠 38×2 가 겹쳐 검은 막대가 된다 | |

### ★ SS2D 지형 배치 기하 규칙 7 가지 (전부 실제로 한 번씩 터진 것 — 반드시 지킨다)

1. **높이차는 "이웃한 두 표면" 사이에서 잰다.** 오목한 자리 옆 블록이면 실제 상승은 두 배다.
2. **틈을 바닥까지 뚫지 마라.** 바닥에 박힌 가구 사이 틈 = 폭 150 짜리 우물. 한 덩어리 + 깊이 110 홈으로.
3. **공중 발판은 `윗면 + 두께 + 48 ≤ 아래 표면`.** (48 = collision_size 24 양쪽)
   → **겹치는 두 층의 윗면 간격 ≥ 160 + 48 + 144 = 352.**
4. **바닥에 박힌 덩어리는 바닥을 좌우로 가른다.** 오른쪽 끝을 바닥까지 내려오는 계단으로 마감한다.
5. `_계단덩어리()` 에서 **같은 높이가 연달아 오면 점이 중복**되어
   `offset_polygon()` 이 빈 배열을 돌려준다 → 그림은 멀쩡한데 **밟을 수 없다.** 같은 높이는 합친다.
6. **`레벨검사` 는 설계 간격에 최대 +44 를 얹어 잰다** (설계 180 → 실측 224 → 한계 204 초과).
7. 다각형이 **자기를 관통하면** 삼각분할이 실패해 fill 메시가 안 구워지고 **속 빈 윤곽선**만 남는다.
   → **진단 신호: `진단_지형메시.gd` 의 "메시" 열이 2 가 아니라 1 이면 그 지형은 실패한 것이다.**

### ★ v5 에서 새로 성립하는 것 — 공중 발판

v4 는 층고 1062 라 겹치는 두 층 사이 352 가 안 나와서 **공중 발판을 전부 포기**했다.
v5 는 층고 2678 → **352 × 4.7 층**. 지그재그·공중 발판·낮은 천장이 전부 성립한다.
단 규칙 3 은 그대로다: **같은 x 를 공유하는 두 발판의 윗면 간격은 352 이상.**
그보다 촘촘한 지그재그가 필요하면 **x 를 겹치지 않게** 어긋 배치한다.

## 3.4 재질 규칙 (도형님 §3 그대로)

| 재질 | 쓰는 곳 | 이번 스테이지 예 |
|---|---|---|
| **WOOD** (`TEMPLATE_WOOD_SOLID` / `_STAIRS`) | 밟고 이동하는 주요 지형 + 가구형 플랫폼 | 책장·옷장·서랍·책상·침대·궤짝·선반·매트리스·파괴가능바닥 |
| **BRICK** (`벽돌 테스` / `벽돌 계단`) | 구조·이동 제한 | 외곽 벽·천장·기둥·**벽에서 튀어나온 선반**·낮은 천장 매스·가시의 기반 |
| GRASS | **금지** | — |

**직사각형 나열 금지.** 계단덩어리(`_계단덩어리`)로 돌출부·오목부·경사·불규칙 가구 실루엣을 만든다.

## 3.5 카메라 규칙

- 스테이지 기본 줌 **1.00**.
- 구간마다 `카메라_공간` 1~2 개. `틈새빛_사용 = false` **필수**.
- 줌은 공간의 성격으로 정한다. **구간이 바뀐 것이 줌으로 읽혀야 한다.**

| 구간 | 줌 | 이유 |
|---|---|---|
| 1-1 | 1.15 | 벽을 타고 내려오는 좁은 등반 — 발밑이 보여야 한다 |
| 1-2 | **0.85** | 창이 통째로 보여야 빛과 바람의 출처가 읽힌다 |
| 1-3 | 1.10 | 가구 밑을 기어가는 구간 — 낮은 천장이 답답해야 한다 |
| 1-4 | 0.95 | 튀어 오르는 높이가 화면에 들어와야 한다 |

## 3.6 조명 규칙

- 광원은 **창문 하나**가 원칙이다. 그 밖에 등불을 늘리지 않는다 (v2 에서 "빛 쏘는 구슬" 사고).
- `빛기둥` 은 `모드_.연출` + `구멍_그리기 = false`. 판정은 별도 Area2D 가 한다.
- 출구(1-4 오른쪽 아래)에는 **광원을 두지 않는다** — 어두워지는 것으로 끝을 알린다.

## 3.7 색 규칙 (§1.10 결론)

- 모든 지형 `칠하기_허용 = false`. **예외: `SS_WOOD_BREAK_FLOOR_01` 하나만 true.**
- ColorZone·빛경계 **안 쓴다** (STAGE 3 부터).
- → 이 스테이지에서 총은 **"바닥을 부수는 도구"** 로만 등장한다. 색 퍼즐 없음.

---

# STEP 4 — Stage 1-1 Guideline · **Zigzag Entry**

> 원화 좌상단 사분면 (원화 x 0…1067 · py 0…600) · world **x −500 … 3096 · y −2570 … −1900**
> 컨셉: *쥐가 벽 구멍으로 들어와, 벽 선반과 가구 윗면을 지그재그로 밟고 내려온다.*

## 4.1 플레이 흐름  ★2026-08-30 제작 완료 — 아래는 **실제 빌드된 값**이다

| 단계 | 내용 | x | y |
|---|---|---|---|
| 진입 | 왼쪽 벽 구멍에서 나온다. 방 전체가 아래로 펼쳐져 보인다 | −500 … 0 | −2400 |
| 공간 파악 | 벽돌 선반 2 단을 걸어 내려온다 (하강 110) | 0 … 770 | −2400 → −2290 |
| **낮은** | 낙차 347 로 책장 윗면에 내려선다 | 900 … 1200 | **−1943** |
| **중간** | 책장 위 책 더미로 한 칸 (같은 덩어리 안) | 1200 … 1500 | **−2053** |
| **높은** | 옷장 위 — 이 구간의 꼭대기 | 1650 … 2050 | **−2163** |
| **다시 낮은** | 옷장을 내려와 가시 받침으로 | 2050 … 2900 | −2053 → **−1943** |
| 출구 | 들보(아랫면 −2030) 밑을 지나 1-2 로 | 3050 … 3396 | **−1860** |

★ **난이도 상승 문법**(다음 STEP): 서랍 A(안전하게 경험) → 서랍 B(가시와 함께) → 1-2 에서 조합.

## 4.2 Terrain Layout (SS2D) — 실제 빌드값

| 노드 이름 | Template | world x0 … x1 | 윗면 y | 두께 | 칠하기 |
|---|---|---|---|---|---|
| `벽_왼위_BRICK_01` | BRICK | −500 … 0 | 천장 → −2570 | | false |
| `벽_왼아래_BRICK_01` | BRICK | −500 … 0 | **−2400** → 바닥 | | false |
| `SS_BRICK_LEDGE_A_01` | BRICK | 0 … 320 | **−2400** | 160 | false |
| `SS_BRICK_LEDGE_B_01` | BRICK | 470 … 770 | **−2290** | 160 | false |
| `SS_WOOD_BOOKSHELF_01` | WOOD_SOLID | 900 … 1500 | **−1943 / −2053** (2 단) | 바닥까지 | false |
| `SS_WOOD_WARDROBE_01` | WOOD_SOLID | 1650 … 2450 | **−2163 / −2053** (2 단) | 바닥까지 | false |
| `SS_BRICK_SPIKE_BASE_01` | BRICK | 2600 … 2900 | **−1943** | 160 | false |
| `SS_BRICK_LEDGE_EXIT_01` | BRICK | 3050 … 3396 | **−1860** | 160 | false |
| `천장들보_경계_1_1_1_2_BRICK_01` | BRICK | 3096 … 3396 | 천장 → **−2030** | | false |

### ⚠ 규칙 3 함정 — 어떻게 풀었나

초안은 벽선반 C(−2180)와 책장 윗면(−1943)이 x 940…1260 에서 겹쳤고
간격 237 < 352 라 **책장 윗면이 밟을 수 없는 면**이 됐다.

→ **해결안 ②(벽선반 C 삭제) + ①(책장 x 이동) 을 둘 다 썼다.**
  선반A(0…320) · 선반B(470…770) · 책장(900…1500) · 옷장(1650…2450) ·
  가시받침(2600…2900) · 출구선반(3050…3396) — **x 가 하나도 안 겹친다.**
  대신 지그재그의 높이차는 **한 덩어리 안의 계단**(책장 2 단 · 옷장 2 단)으로 만들었다.
  같은 덩어리 안이면 간격 0 이라 규칙 3 이 아예 적용되지 않는다.

### 이름 규칙 함정 (실제로 걸렸다)

`레벨검사.gd` 의 `구조물_접두 = ["천장", "굴뚝벽", "벽", "받침"]` 때문에
**`벽선반_A` 처럼 "벽" 으로 시작하면 도달 검사에서 통째로 빠진다.**
→ 밟으라고 만든 발판은 `SS_` 로, 진짜 구조물(들보)은 `천장…` 으로 이름 지었다.

## 4.3 Gimmick A — 움직이는 서랍 (`서랍_A` / `서랍_B`)

### 도형님 질문에 대한 답: **"서랍 전체의 Collision 을 끄는 방식"은 쓰지 않는다**

이유 3 가지 — 전부 이 프로젝트에서 실제로 문제가 되는 것이다.

1. **밟고 선 발밑에서 콜리전을 끄면 플레이어가 한 프레임 만에 떨어진다.** 원인이 화면에 안 읽힌다.
2. **`레벨검사.gd` 는 물리 프레임 한 장을 스캔한다.** 시간에 따라 변하는 콜리전은 아예 못 본다.
   → "열린 상태에서만 갈 수 있는 길"은 검사기가 [도달불가]로 잡거나, 반대로
     닫힌 상태를 못 봐서 **거짓 통과**를 낸다. 검사기를 못 믿게 되면 이 프로젝트의 안전망이 사라진다.
3. 이 게임에는 **콜리전을 끄는 문법이 이미 하나 있다** — `무색일때_통과`(유령 발판, 레이어 8).
   같은 뜻을 두 가지 방식으로 표현하면 플레이어가 규칙을 못 배운다.

### 그래서 이렇게 만든다 — **서랍은 물리적으로 미끄러져 나온다**

`scenes/장애물/움직이는발판.tscn` (`AnimatableBody2D` · **기존 스크립트 그대로**) 를 인스턴스한다.

| 설정 | 값 | 이유 |
|---|---|---|
| `이동방향` | 0 (가로) | 서랍은 옆으로 나온다 |
| `이동거리` | **150** | 딱 틈 하나를 메운다 |
| `왕복시간` | **4.0** (A) / **3.0** (B) | B 가 더 빠르다 = 난이도 상승 |
| `시작지연` | 0.0 (A) / 1.2 (B) | 두 서랍이 동기화되지 않게 |
| 콜리전 | layer **1** / mask 0 | 기존 규약. 밟을 수 있는 지형 |

★ **윗면은 언제나 단단하다.** 바뀌는 것은 위치뿐이라 위 3 가지 문제가 전부 사라진다.
★ **틈 150 은 서랍이 닫혀 있어도 뛰어 건널 수 있다** → `레벨검사` 가 항상 통과한다.
  서랍은 "쉽게 가는 길"이지 "유일한 길"이 아니다. 튜토리얼 구간의 첫 기믹에 맞는 강도다.

`[확인 필요]` `움직이는발판.gd` 는 `AnimatableBody2D` 를 직접 움직인다. 그 위에 선 플레이어가
같이 실려 가는지(`sync_to_physics`)는 이 축척에서 한 번 눈으로 확인해야 한다.
안 실리면 서랍 위에서 미끄러지는데, 폭 150 짜리 서랍에서는 그것도 나쁘지 않다 — **확인 후 결정.**

## 4.4 Gimmick B — Brick Spike Trap (`가시_1_1`)

### 도형님 질문에 대한 답: **지형 콜리전과 데미지 판정을 완전히 분리한다**

| 노드 | 타입 | Layer / Mask | 역할 |
|---|---|---|---|
| `SS_BRICK_SPIKE_BASE_01` | SS2D BRICK (`벽돌 테스`) | **1 / 0** | **가시가 박힌 받침**. 실제로 밟히는 단단한 지형 |
| `가시_1_1` | `scenes/장애물/가시.tscn` (Area2D) | **0 / 1** | **데미지 판정만.** 밀어내지 않는다 |

- 가시 자체는 **절대 지형이 아니다.** 뾰족한 것 위에 올라설 수 있으면 함정이 아니다.
- `가시.tscn` 설정: `방향 = 0(위)` · `칸수 = 4` (= 128 px) · `가시높이 = 26`
- 받침 위에 얹되 **가시 끝이 옆 발판 윗면(−1937)보다 아래**에 오게 둔다 → 스쳐도 안 죽는다.
- ⚠ **§1.11 (A) 의 `월드.gd` 4 줄이 들어가야 실제로 죽는다.** 그 전에는 그림만 나온다.

## 4.5 Collision 표

| Object | Node | Collision Layer | Collision Mask | 역할 |
|---|---|---|---|---|
| 벽·선반·옷장·책장 | SS2D → StaticBody2D | **1** | 0 | 밟는 지형 |
| 서랍 A/B | AnimatableBody2D | **1** | 0 | 움직이는 지형 |
| 가시 받침 | SS2D → StaticBody2D | **1** | 0 | 밟는 지형 |
| 가시 | Area2D (`가시.gd`) | **0** | **1** | 즉사 판정 (group `hazard`) |
| 카메라 공간 | Area2D (`카메라_공간.gd`) | **0** | **1** | 줌 전환 |

**새 레이어 없음.**

## 4.6 난이도

**2 / 10.** 죽을 수 있는 곳은 가시 한 군데. 틈은 전부 150(안전 218 의 69 %).
실패해도 아래 옷장 윗면으로 떨어질 뿐이고, 옷장 옆면 계단(110)으로 다시 오른다.

---

# STEP 5 — Stage 1-2 Guideline · **Window Light & Wind**

> 원화 우상단 사분면 · world **x 3096 … 6192 · y −2570 … −1150**
> 컨셉: *창에서 쏟아지는 빛이 쥐를 밀어내고, 창틈에서 새는 바람이 몸을 띄운다.*
> 진행: 오른쪽으로 나갔다가 **한 층 아래로 내려와 왼쪽으로 되돌아온다** (가이드 이미지의 나선).

## 5.1 플레이 흐름

| 단계 | 내용 | x | y |
|---|---|---|---|
| 진입 | 옷장 끝 평지에서 벽 선반으로 | 3096 | −1930 |
| 공간 파악 | 빈 벽(3094…4002)의 Brick 돌출부 2 단. **창이 화면에 통째로 들어온다** | 3096 … 4000 | −1930 |
| **기믹 학습 ①** | 빛 가장자리를 스치는 **넓은 선반(폭 500)**. 밀려도 안 떨어진다 = 안전하게 체험 | 4000 … 4500 | −1930 |
| **기믹 학습 ②** | 커튼(좌) 주름 발판. **창틈 바람**이 위로 분다 — 그냥 서 있으면 둥실 뜬다 | 4298 … 4585 | −1885 |
| 기믹 활용 | 바람으로 체공을 늘려 **틈 240** 을 건너 커튼봉으로 (평소 한계 150) | 4585 … 4825 | −1929 |
| **위험 구간** | 창 위를 커튼봉으로 횡단. 빛 넉백이 **아래로+왼쪽으로** 민다 | 4825 … 5510 | −1929 |
| 하강 | 커튼(우) 주름 → 창턱 중단 → 창 가로살 (낙차 330 씩) | 5510 → 4614 | −1929 → −1191 |
| 안전 구간 | 창 가로살에서 왼쪽 벽 선반으로. 빛 밖 | 4614 … 3096 | −1191 |

## 5.2 Terrain Layout

| 노드 이름 | Template | x0 … x1 | 윗면 y | 두께 | 비고 |
|---|---|---|---|---|---|
| `벽선반_E_BRICK_01` | BRICK | 3096 … 3550 | −1930 | 160 | |
| `벽선반_F_BRICK_01` | BRICK | 3700 … 4000 | −1930 | 160 | 틈 150 |
| `SS_BRICK_LIGHT_LEDGE_01` | BRICK | 4000 … 4500 | −1930 | 160 | **폭 500 안전 선반** |
| `SS_WOOD_CURTAIN_L_01` | WOOD_STAIRS | 4298 … 4585 | −1885 | 200 | 커튼 주름 (§7 "커튼은 짧은 발판") |
| `SS_WOOD_CURTAIN_ROD_01` | WOOD_SOLID | 4825 … 5510 | **−1929** | 170 | 커튼봉 = 창 위 횡단로 |
| `SS_WOOD_CURTAIN_R_01` | WOOD_STAIRS | 5388 … 5560 | −1599 | 200 | 낙차 330 |
| `SS_BRICK_WINSILL_MID_01` | BRICK | 4900 … 5400 | −1269 | 160 | 낙차 330 |
| `SS_BRICK_WINBAR_01` | BRICK | 4614 … 5542 | **−1191** | 160 | **창 가로살** — 창틀에 실제로 있는 것 |
| `벽선반_G_BRICK_01` | BRICK | 4150 … 4500 | −1191 | 160 | 왼쪽 귀환로 |
| `벽선반_H_BRICK_01` | BRICK | 3700 … 4000 | −1191 | 160 | 틈 150 |
| `벽선반_I_BRICK_01` | BRICK | 3096 … 3550 | −1191 | 160 | 1-3 인계 지점 |

### ⚠ 규칙 3 검산 (상단 −1930 층 vs 귀환 −1191 층)

같은 x 를 공유하는 두 층: `벽선반_F`(3700…4000, −1930) vs `벽선반_H`(3700…4000, −1191).
간격 = **739 ≥ 352** ✔. `E`(−1930) vs `I`(−1191) 도 같다 ✔.
**커튼봉(−1929)** 과 **창 가로살(−1191)**: 간격 738 ✔.

## 5.3 Gimmick C — Light Knockback (`빛밀어냄_창`)

### ★설계 결론 — 수평 넉백은 `velocity.x` 로 주면 안 된다

§1.3 에서 확인했듯 `player.gd` 는 매 프레임 `velocity.x = dir * move_speed` 로 x 를 **통째로 덮어쓴다.**
→ `velocity.x` 에 넉백을 넣으면 **다음 프레임에 사라진다.** 도형님이 §7 에서 걱정한
"바닥에서 미끄러지는 문제 / 무한히 밀리는 문제"는 여기서 자동으로 해결되지만, 동시에 **효과 자체가 안 난다.**

**→ 수평은 `move_and_collide()` 로 직접 민다.** `CharacterBody2D` 의 메서드라
   벽·지형에 부딪히면 알아서 멈춘다(터널링 없음). `velocity` 를 건드리지 않으므로
   `player.gd` 는 **한 줄도 안 고친다.**

```gdscript
# scripts/스마트월드/빛_밀어냄.gd (신규 · 약 55 줄)
@tool
extends Area2D
class_name 빛밀어냄
## 창에서 들어오는 빛에 밀린다.
## ▣ 왜 velocity 를 안 쓰나
##   player.gd 는 매 물리 프레임 `velocity.x = dir * move_speed` 로 x 를 덮어쓴다.
##   그래서 수평 넉백을 velocity.x 에 넣으면 다음 프레임에 지워져 아무 일도 안 일어난다.
##   → 수평은 move_and_collide() 로 실제 이동을 시킨다 (벽에 부딪히면 알아서 멈춘다).
##   → 수직은 velocity.y 에 직접 더한다. 중력만 누적될 뿐 덮어쓰이지 않기 때문이다
##     (도약대.gd 가 2026-08-06 부터 같은 방식으로 잘 돌고 있다).
@export var 광원_위치: Vector2 = Vector2.ZERO   ## 창 중심(로컬). 여기서 바깥으로 민다
@export var 세기: float = 260.0                 ## px/초. ★가속이 아니라 속도다 — 무한 가속 방지
@export var 수직_비율: float = 0.35             ## 수평 대비 수직 성분
@export var 공중_배수: float = 1.6              ## 점프 중에는 더 세게 = "빛에 뜬다"
```

| 도형님 검토 항목 | 이 설계의 답 |
|---|---|
| Knockback 방향 | **창 중심에서 플레이어로 향하는 방향**을 매 프레임 계산 → 항상 "빛에서 바깥으로" |
| Knockback Strength | `세기` 260 px/s = move_speed(390)의 67 %. **걸어서 거스를 수 있다** = 좌절하지 않는다 |
| 수평 / 수직 | 수평 = `move_and_collide` · 수직 = `velocity.y` 가산 (`수직_비율` 0.35) |
| 지속형 / 순간형 | **지속형.** 순간형은 "왜 밀렸는지" 안 읽힌다 |
| 영역 내 반복 적용 | **속도(px/초)라서 누적되지 않는다.** 가속(px/s²)으로 주면 무한히 빨라진다 — 그래서 안 쓴다 |
| 무한히 밀리는 문제 | 위와 동일 + `move_and_collide` 가 벽에서 멈춘다 |
| 바닥에서 미끄러지는 문제 | `move_and_collide` 는 바닥 마찰과 무관하다. 밀린 만큼만 이동하고 멈춘다 |
| 벽에 부딪혔을 때 | `move_and_collide` 반환값이 충돌이면 그 프레임은 거기서 끝 |
| 점프 중 처리 | `공중_배수 1.6` — 발이 떨어져 있으면 더 세게. **"떠 있으면 빛에 휩쓸린다"** 가 규칙이 된다 |

### 배치
- 판정 Area2D: 창(4614…5542)에서 왼쪽 아래로 퍼지는 **사다리꼴 CollisionPolygon2D** 1 개.
  `광원_위치` = 창 중심 `(5078, −1191)`.
- 연출: `빛기둥.gd` `모드_.연출` · `구멍_그리기 = false` · 각도 100° · 세기 0.78.
  **판정과 연출은 다른 노드다** — 이 프로젝트의 기존 문법 그대로(v4 `_창문과_경계()` 참고).

## 5.4 Gimmick D — Window Wind (`바람_창틈`)

### 설계 결론: **Gravity Point 도 Linear Velocity 도 쓰지 않는다**

- `Area2D` 의 `gravity_point` / `linear_damp` 등 **공간 오버라이드는 RigidBody2D 에만 먹는다.**
  플레이어는 `CharacterBody2D` 라 **아무 영향도 안 받는다.** (도형님 §7 의 선택지 중 둘은 여기서 탈락)
- → 남는 것은 직접 velocity 수정. 그리고 §1.3 대로 **수직은 안전하다.**

```gdscript
# scripts/스마트월드/바람지대.gd (신규 · 약 45 줄)
@tool
extends Area2D
class_name 바람지대
## 창틈에서 새는 바람. **밀지 않고 띄운다.**
## ▣ 왜 "밀기"가 아니라 "체공"인가 (도형님 §7 지시)
##   미는 바람은 빛 넉백과 감각이 겹친다. 바람은 **떠 있는 시간**을 늘려
##   "평소엔 못 건너는 틈을 건널 수 있게" 만드는 쪽이 레벨 문법으로 훨씬 낫다.
## ▣ 어떻게
##   상승 중(velocity.y < 0)에는 중력의 일부를 상쇄하고, 하강은 상한을 걸어 늦춘다.
##   velocity.y 만 만진다 — player.gd 는 y 를 덮어쓰지 않으므로 안전하다(도약대와 같은 방식).
@export var 뜨는힘: float = 900.0        ## px/s² — 중력 2288 의 39 %
@export var 최대_하강속도: float = 220.0 ## 이 이상 빨리 못 떨어진다 = 둥실 뜬다
@export var 수평_흐름: float = 0.0       ## 0 이면 순수 수직 바람
```

- 배치: 창 아랫틀 틈(x 4614…5542) 위로 올라가는 **세로 기둥 Area2D**, 높이 700.
- 효과 검산: 체공 0.63 초 → 하강속도 상한 220 이면 체공 약 **1.1 초** → 수평 도달 390 × 1.1 = **429 px**.
  → 틈 240 을 여유 있게 건넌다. 바람 밖에서는 여전히 150 이 한계.
  ★ **"바람 안에서만 건널 수 있는 틈"** 이 성립한다 = 기믹이 레벨의 문법이 된다.

⚠ `레벨검사.gd` 는 바람을 모른다 → **틈 240 을 [도달불가]로 보고할 것이다.**
  이것은 **알고 넘기는 예외 1 건**이다. 보고서에 남기고, 그 틈 아래에 받아주는
  넓은 선반(`SS_BRICK_LIGHT_LEDGE_01`)을 둬서 실패해도 죽지 않게 한다.

## 5.5 Collision 표

| Object | Node | Collision Layer | Collision Mask | 역할 |
|---|---|---|---|---|
| 벽 선반·커튼봉·창살 | SS2D → StaticBody2D | **1** | 0 | 밟는 지형 |
| `빛밀어냄_창` | Area2D (신규) | **0** | **1** | 넉백 (밀기만, 안 죽인다) |
| `바람_창틈` | Area2D (신규) | **0** | **1** | 체공 연장 |
| `창빛_연출` | `빛기둥.gd` 모드=연출 | **0** | 0 | 그림만 |
| 창문 프리팹 | `창문_배경.tscn` 등 | — | — | 배경 |

**새 레이어 없음.**

## 5.6 난이도

**5 / 10.** 이 스테이지의 정점. 실패 지점은 (a) 커튼봉 횡단 중 빛에 밀려 낙하,
(b) 바람 틈 건너기 실패. 둘 다 아래 넓은 선반이 받아준다 → **낙차 ≤ 390 으로 설계** (즉사 없음).

---

# STEP 6 — Stage 1-3 Guideline · **Bookshelf Obstacles**

> 원화 좌하단 사분면 · world **x 0 … 3096 · y −1191 … 0**
> 컨셉: *가구 밑을 기어 다니는 쥐.* 넓은 공간 → 낮은 천장 → 좁은 통로 → 넓은 공간.
> 진행: 창 쪽에서 **왼쪽으로 내려와 바닥에 닿고, 바닥을 따라 오른쪽으로 되돌아온다** (가이드 panel 3 의 S 자).

## 6.1 플레이 흐름

| 단계 | 내용 | x | y |
|---|---|---|---|
| 진입 | 벽 선반 −1191 에서 왼쪽으로 | 3096 → 2790 | −1191 |
| 하강 ① | 침대 헤드보드 위로 (낙차 417 ⚠ → 중간 선반 하나 넣어 2 단으로) | 2790 | −1191 → −774 |
| 하강 ② | 헤드보드 → 매트리스 (낙차 464 ⚠ → 2 단) | 2790 → 2600 | −774 → −310 |
| 하강 ③ | 매트리스 → 궤짝 → 바닥 | 2610 → 2300 | −310 → 0 |
| **기믹 학습** | **옷장 밑 (낮은 천장 480)** 을 걸어서 통과. 위험 없음 | 2291 → 1491 | 0 |
| 공간 리듬 | 넓은 바닥(1341…1491) → **책장 밑 좁은 통로(높이 200)** | 1341 → 745 | 0 |
| **위험 구간** | **굴러오는 연필.** 책상(0…754, −493) 에서 주기적으로 굴러떨어져 바닥을 굴러온다 | 745 → 0 | 0 |
| 반환점 | 책장 왼쪽 면의 선반 4 단을 타고 **책장 위로 올라간다** = "책장을 넘어감" | 745 … 1045 | 0 → −550 |
| 안전 구간 | 책장 중단 선반(−550)에서 오른쪽으로. 연필이 못 올라온다 | 1045 → 2291 | −550 |
| 인계 | 궤짝 위(−261) → 바닥 → 1-4 | 2291 → 3096 | −261 → 0 |

`[확인 필요]` 낙차 417·464 는 설계 상한 330 을 넘는다 → **중간 선반을 하나씩 더 넣어 2 단으로 쪼갠다.**
정확한 x/y 는 §STEP 10 의 3 단계에서 `레벨검사` 를 돌려 확정한다.

## 6.2 Terrain Layout

| 노드 이름 | Template | x0 … x1 | 윗면 y | 비고 |
|---|---|---|---|---|
| `SS_WOOD_BEDHEAD_01` | WOOD_STAIRS | 2662 … 2788 | −774 | 침대 헤드보드 |
| `SS_WOOD_MATTRESS_01` | WOOD_SOLID | 2337 … 3932 | **−310** | ★1-4 에서 트램폴린이 된다 · §7.3 곡선 |
| `SS_WOOD_CRATE_01` | WOOD_STAIRS | 2291 … 2610 | −261 | 궤짝 |
| `SS_WOOD_WARDROBE_BODY_01` | WOOD_SOLID | 1491 … 2291 | −1937 (아랫면 **−480**) | **낮은 천장 ①** — 다리로 떠 있다 |
| `SS_WOOD_BOOKSHELF_BODY_01` | WOOD_STAIRS | 745 … 1341 | −1943 (아랫면 **−200**) | **낮은 천장 ②** — 좁은 통로 |
| `SS_WOOD_BOOKSHELF_STEP_01~04` | WOOD_STAIRS | 745 … 1045 | −220 / −330 / −440 / −550 | **책장 왼쪽 면의 선반 4 단** = 오르는 길 |
| `SS_WOOD_DESK_01` | WOOD_SOLID | 0 … 754 | −493 | 책상 — 연필 발사대 |
| `SS_BRICK_CEIL_LOW_01` | BRICK | 400 … 745 | 아랫면 −250 | **낮은 천장 ③** — 천장에서 내려온 Brick 구조물 |
| `바닥_STAGE1_BRICK_01` | BRICK | −500 … 6692 | **0** (두께 300) | ★끊김 없는 하나의 평지 |

### ★ Brick Ceiling — 공간의 리듬 (도형님 §8)

```
  넓은 바닥 805        낮은 천장 480      숨통 150     좁은 통로 200      넓은 바닥 745
├──────────────┤ ├───────────────┤ ├────────┤ ├─────────────┤ ├───────────────┤
   2291 … 3096         옷장 밑          1341…1491      책장 밑          0 … 745
   위가 보인다        머리가 막힌다      한 번 열림      기어간다        다시 열린다
```
- 실효 높이 = 표기값 − 48(콜리전 부풀림). 200 − 48 = **152 > 96** ✔ 지나갈 수 있다.
- 200 은 **점프를 못 하는 높이**다(점프 167). → 낮은 천장이 **점프를 봉인**한다 = 도형님 §8 의 요구.

## 6.3 Gimmick E — Rolling Pencil (`연필공장_책상`)

```
scenes/집/스마트월드_장애물/연필.tscn (신규)
└ 연필 (RigidBody2D · layer 1 · mask 1)     ← 굴러야 하니까 진짜 강체
  ├ CollisionShape2D (CapsuleShape2D · 반지름 14 · 높이 90 · 90° 회전)
  ├ 그림 (Sprite2D + 아트슬롯.gd, 비면 _draw() 가 그린다 — 기존 문법)
  └ 판정 (Area2D · layer 0 · mask 1) ─ group "hazard"
```

```gdscript
# scripts/스마트월드/굴러오는연필.gd (신규 · 약 60 줄) — 스포너
@tool
extends Node2D
class_name 굴러오는연필
## 책상에서 주기적으로 연필이 굴러떨어진다.
## ⚠ 매 프레임 instantiate 하지 않는다 — Timer 하나로 주기를 만들고,
##   살아 있는 개수를 세어 상한을 넘으면 가장 오래된 것부터 지운다.
@export var 주기: float = 3.2           ## 초
@export var 최대_개수: int = 4          ## 이 이상 쌓이지 않는다
@export var 수명: float = 9.0           ## 개체 스스로도 이 시간 뒤 사라진다
@export var 초기_속도: Vector2 = Vector2(-120, 0)
@export var 즉사: bool = false          ## ★기본은 "죽이지 않고 밀어낸다"
```

### 도형님 §8 의 요구 대응

| 요구 | 대응 |
|---|---|
| 매 프레임 instantiate 금지 | `Timer` 하나. `주기` 3.2 초 |
| Lifetime | 개체마다 `수명` 9 초 |
| Maximum Count | `최대_개수` 4. 초과분은 **가장 오래된 것부터** `queue_free()` |
| Cleanup | 스포너가 `_생성목록: Array[Node]` 로 직접 관리. 씬이 사라지면 자식이라 같이 사라진다 |

### ★ `즉사` 기본값을 false 로 두는 이유

STAGE 1 은 난이도 1~3 튜토리얼이다. 낮은 천장 아래(점프 봉인)에서 즉사 물체가 굴러오면
피할 수단이 **없다**. → 기본은 **넉백**(빛 넉백과 같은 `move_and_collide` 방식, 세기 300).
`즉사 = true` 로 켜는 것은 도형님 판단으로 남긴다. **켜면 §1.11 (A) 수정이 필요하다.**

## 6.4 Collision 표

| Object | Node | Collision Layer | Collision Mask | 역할 |
|---|---|---|---|---|
| 가구 본체·바닥·낮은 천장 | SS2D → StaticBody2D | **1** | 0 | 지형 |
| 연필 | RigidBody2D | **1** | **1** | 지형 위를 실제로 구른다 |
| 연필 판정 | Area2D (자식) | **0** | **1** | 넉백 또는 즉사 (group `hazard`) |
| 스포너 | Node2D | — | — | Timer 만 |

**새 레이어 없음.** ⚠ 연필이 `layer 1` 이므로 **플레이어가 연필을 밟을 수 있다.**
이건 의도다 — 굴러오는 연필을 밟고 넘는 것이 이 구간의 재미다.

## 6.5 난이도

**4 / 10.** 낮은 천장 + 굴러오는 물체의 조합. 즉사는 없다(기본값 기준).
바닥이 끊김 없는 하나의 평지라 **소프트락이 생길 자리가 없다.**

---

# STEP 7 — Stage 1-4 Guideline · **Descent to 1st Floor**

> 원화 우하단 사분면 · world **x 3096 … 6192 · y −900 … 0**
> 컨셉: *매트리스에서 튀어 올라 선반을 밟고, 마지막에 마룻바닥을 쏘아 부수고 1층으로 떨어진다.*

## 7.1 플레이 흐름

| 단계 | 내용 | x | y |
|---|---|---|---|
| 진입 | 바닥에서 매트리스 옆으로 | 3096 | 0 |
| **기믹 학습** | 매트리스에 올라선다 → **가만히 있으면 안 튄다.** 위에서 떨어져야 튄다 | 3200 … 3932 | −310 |
| 기믹 활용 | 튀어서 **선반 A(−720)** 로. 실패해도 매트리스로 되떨어진다 = 무한 재시도 | 4100 … 4400 | −720 |
| 위험 구간 | 선반 A → 선반 B(−870) → 탁자(−493). 아래는 매트리스가 아니다 | 4400 … 5300 | −870 → −493 |
| 안전 구간 | 탁자 위 평지 (폭 700). 오른쪽 벽 앞 | 5300 … 6000 | −493 |
| **최종 관문** | 탁자 오른쪽 아래 **파괴 가능 마룻바닥.** 총으로 부순다 | 5700 … 6192 | 0 |
| 스테이지 끝 | 뚫린 구멍으로 **1층으로 낙하** → `연결통로` 로 STAGE 2 | 5900 | 0 → |

## 7.2 Terrain Layout

| 노드 이름 | Template | x0 … x1 | 윗면 y | 비고 |
|---|---|---|---|---|
| `SS_WOOD_MATTRESS_01` | WOOD_SOLID | 2337 … 3932 | **−310** | ★**곡선.** §7.3 |
| `SS_WOOD_SHELF_A_01` | WOOD_SOLID | 4100 … 4400 | −720 | 공중 발판 두께 180 |
| `SS_WOOD_SHELF_B_01` | WOOD_SOLID | 4700 … 5000 | **−870** | ⚠ 아래 검산 참고 |
| `SS_WOOD_TABLE_01` | WOOD_STAIRS | 4953 … 6192 | −493 | 원화의 탁자 |
| `SS_WOOD_BREAK_FLOOR_01` | WOOD_SOLID | **5700 … 6192** | **0** | **칠하기_허용 = true · 이 스테이지 유일** |
| `벽_오른_BRICK_01` | BRICK | 6192 … 6692 | 천장 → 바닥 | |

### 규칙 3 검산
- `SHELF_A`(−720, 두께 180 → 아랫면 −540) 아래 표면 = 매트리스(−310).
  간격 720 − 310 = **410 ≥ 352** ✔ 매트리스 위를 걸어 다닐 수 있다.
- `SHELF_B` 를 −830 으로 두면 아래 탁자(−493)와 간격 337 **< 352** ✘
  → **−870 으로 올린다** (간격 377 ✔). 이것이 위 표의 값이다.

## 7.3 Mattress — 곡선 SS2D

도형님 §9: *"SmartShape2D 의 곡선 / Bezier 기반 형태를 활용하여 부드럽게 휘어진 플랫폼."*

**구현:** 빌더에 `_곡선덩어리()` 를 새로 만든다 (`_계단덩어리()` 의 형제).

```gdscript
## 부드럽게 처진 매트리스 윗면. 사인 반주기로 샘플링해 점을 찍는다.
## ★베지어 제어점(SS2D_Point 의 point_in/point_out)을 쓰지 않고 **점을 촘촘히 찍는** 이유:
##   ① 제어점을 쓰면 `get_tessellated_points()` 결과와 콜리전 생성 결과가 갈릴 수 있어
##      "보이는 것과 밟는 것이 다른" 상태를 다시 만들 위험이 있다 (이 프로젝트가 이미 겪은 사고).
##   ② 규칙 5 — 같은 높이가 연달아 오면 점이 중복돼 offset_polygon() 이 빈 배열을 낸다.
##      샘플링하면 인접 점의 y 가 자연히 다르므로 그 함정을 피한다(정점 1 개만 중복 제거).
func _곡선덩어리(x0: float, x1: float, 윗면y: float, 처짐: float,
		바닥: float, 칸: int = 14) -> PackedVector2Array
```

- `처짐 = 60` (양 끝보다 가운데가 60 px 낮다) · `칸 = 14` (칸 폭 114 px)
- ⚠ 규칙 6 — 검사기는 이웃 표면점을 26 px 허용으로 묶는다. 칸당 y 변화가 26 을 넘으면
  **선반이 잘게 쪼개져** 보고서가 시끄러워진다. 처짐 60 / 칸 14 이면 칸당 최대 ≈ 13 px ✔

## 7.4 Gimmick F — Trampoline

### 도형님 §9 의 두 방법 비교 — **결론: 1 번은 아예 작동하지 않는다**

| 방법 | 판정 | 이유 |
|---|---|---|
| ① `PhysicsMaterial` 의 `bounce` | ❌ **불가** | `bounce` 는 **RigidBody2D 끼리의 충돌 반발**에만 쓰인다. 플레이어는 `CharacterBody2D` 이고 `move_and_slide()` 는 PhysicsMaterial 을 **전혀 읽지 않는다.** |
| ② Area2D 감지 + 직접 velocity 수정 | ✅ **이 방법뿐이다** | `velocity.y` 는 `player.gd` 가 덮어쓰지 않는다 (§1.3) |

### ★ 그런데 ② 는 **이미 만들어져 있다** — `scripts/스마트월드/도약대.gd`

```gdscript
# 도약대.gd _physics_process() 의 핵심
for 몸 in get_overlapping_bodies():
    var p := 몸 as CharacterBody2D
    if v.y < -10.0: continue      # 위에서 내려오는 중일 때만 (아래서 머리로 받으면 안 튄다)
    v.y = 도약속도 ;  p.velocity = v ;  _쿨 = 0.18
```
- `collision_layer = 0 / mask = 1` — 기존 규약 준수
- 자식 `발판`(StaticBody2D · layer 1) 이 실제로 밟히는 면 = **판정과 지형이 분리돼 있다**
- `_쿨 0.18` 로 연속 발동 방지 · `색_제한` 을 끄면 색과 무관

**→ 새 스크립트를 만들지 않는다. `scenes/집/스마트월드_장애물/도약대.tscn` 을 인스턴스한다.**

| 설정 | 값 | 검산 |
|---|---|---|
| `폭` | 400 | 매트리스 가운데에 얹는다 |
| `높이` | 60 | |
| `도약속도` | **−1450** | 상승 = 1450² / (2 × 2288 × 1.0) = **459 px** |
| `색_제한` | false | 이 스테이지는 색 퍼즐이 없다 |

★ **459 < 치명 낙하 520** ✔ — 받아줄 발판이 없어도 스스로 죽지 않는다.
★ 매트리스 윗면 −310 + 459 = **−769** → 선반 A(−720) 에 **여유 49 로 닿는다.**
  (`도약대.gd` 주석의 경고: 세기를 치명 거리보다 크게 잡으면 도약대가 자살 장치가 된다 → 안 넘겼다)

⚠ 도약대의 `발판`(StaticBody2D)이 매트리스 SS2D 와 **겹친다.** 도약대를 매트리스 윗면보다
  `높이 × 0.5 = 30` 만큼 위에 놓아 두 콜리전이 안 겹치게 한다. **[확인 필요 — 배치 시 눈으로 확인]**

## 7.5 Gimmick G — Breakable Wooden Floor

### ★ 기존 총 시스템을 **한 줄도 안 고친다** — `명중()` 계약에 올라탄다 (§1.4)

```gdscript
# scripts/스마트월드/부서지는지형.gd (신규 · 약 50 줄)
@tool
extends 스마트지형          ## ★SS2D 지형을 그대로 상속한다 — 아트·콜리전·재질이 전부 따라온다
class_name 부서지는지형
## 총에 맞으면 부서지는 나무 바닥.
## ▣ 왜 지형.gd 를 상속하나
##   총알은 레이어 1|8 을 레이캐스트해서 맞은 바디의 조상 중 `명중()` 을 가진 노드를 찾는다.
##   SS2D 지형은 이미 그 구조([스마트지형] → StaticBody2D → CollisionPolygon2D)를 갖고 있다.
##   → 상속하면 총·총알·페인트코어를 **하나도 안 고치고** 파괴 가능 지형이 된다.
## ▣ 색 규칙과의 관계
##   `칠하기_허용 = true` 여야 총알이 "칠할 수 있는 대상"으로 인식한다.
##   이 스테이지에서 true 인 지형은 **이것 하나뿐**이다 — 그래서 "쏠 곳"이 저절로 읽힌다.
@export var 필요_명중: int = 3        ## 이만큼 맞으면 부서진다
@export var 부서짐_지연: float = 0.25 ## 마지막 명중 뒤 무너지기까지 (연출 여유)
@export var 되살아남: float = 0.0     ## 0 이면 영구 파괴
signal 부서짐()                        ## 1층 낙하 연출을 나중에 붙일 자리

func 명중(색: int, 월드좌표: Vector2) -> String:
    var 결과 := super(색, 월드좌표)   ## 물감 얼룩·번짐 연출은 부모 것을 그대로 쓴다
    _맞은수 += 1
    if _맞은수 >= 필요_명중: _부수기()
    return 결과                        ## "progress"/"painted" — 페인트코어 회수 규칙 유지
```

### 부서지는 방식
1. `부서짐_지연` 동안 흔들린다 (`position` 미세 진동 — `무너지는바위.gd` 와 같은 문법)
2. `StaticBody2D.collision_layer = 0` **(`set_deferred`)** → 밟을 수 없게
   ⚠ 물리 콜백 중 즉시 변경은 Godot 이 막는다. `set_deferred` 필수.
3. `modulate.a` 를 0 으로 트윈 → 사라진다
4. 플레이어가 뚫린 구멍으로 낙하

⚠ **낙하 거리**: 바닥(0) 아래로 떨어지면 `치명_낙하거리 520` 에 걸린다.
→ 구멍 아래에 **`연결통로`(출구)** 를 세운다. 통로에 들어가는 순간 `장면전환` 이
  STAGE 2 를 부르므로 낙하 판정이 성립하기 전에 씬이 바뀐다.
  `[확인 필요]` `연결통로.gd` 가 **세로(아래 방향) 통로**를 지원하는지 — 지금까지 전부 가로였다.
  안 되면 대안: 구멍 아래 200 px 지점에 착지 발판을 두고 그 위에 가로 통로를 놓는다.

## 7.6 Collision 표

| Object | Node | Collision Layer | Collision Mask | 역할 |
|---|---|---|---|---|
| 매트리스·선반·탁자 | SS2D → StaticBody2D | **1** | 0 | 지형 |
| `도약대` 판정 | Area2D (`도약대.gd`) | **0** | **1** | `velocity.y` 수정 |
| `도약대` 발판 | StaticBody2D (자식) | **1** | 0 | 밟는 면 |
| `SS_WOOD_BREAK_FLOOR_01` | `부서지는지형` → StaticBody2D | **1** | 0 | **총 명중 대상.** 부서지면 layer 0 |
| `출구통로` | `연결통로.gd` Area2D | **0** | **1** | 씬 전환 |

**새 레이어 없음.**

## 7.7 난이도 · 1층 연결

**3 / 10.** 도약대가 무한 재시도를 보장한다(실패하면 매트리스로 되떨어진다).
최종 관문은 조작이 아니라 **"총을 쏜다"는 발상**이다 — 이 게임의 핵심 동사를 마지막에 가르친다.

```
챕터.gd 스테이지표 2 번 = res://scenes/집/스테이지_2_복도계단.tscn
빌더 상수:  const 다음씬 := ""      ← STAGE 2 가 아직 없으므로 빈 문자열
                                     (통로는 그림만 그리고 전환하지 않는다)
```

---

# STEP 8 — Main Scene Node Tree

★ 도형님이 §11 에 적어 준 구조를 **이 프로젝트의 실제 문법으로 옮긴** 것이다.
이 프로젝트에는 "Main" 이라는 별도 씬이 없다 — **스테이지 루트가 곧 매니저(`월드.gd`)** 다.

```
스테이지_1_2층방  (Node2D + 월드.gd)          ★ = 도형님의 "Main"
│   스테이지_이름 "1 · 2층 방"
│   카메라_리밋 Rect2(-600, -3078, 7392, 3678) · 카메라_줌 1.00
│   시작_위치 (-260, -2400) · 낙사_y 900 · 치명_낙하거리 520
│   안전지점_자동저장 true
│
├─ 페인트코어            Node (group 페인트코어) · 최대_탄약 12
├─ 어둠                  CanvasModulate ← 챕터.팔레트(1)["어둠"]
│
├─ 배경_먼               Parallax2D  z -45  scroll 0.35
│   └ 실내먼지           안개층.gd
├─ 배경_방벽             Parallax2D  z -40  scroll 0.98
│   └ 벽지_2층방_전체    실내배경.gd  ★★room.png 한 장 · 원본영역 = 전체(0,0,2135,1200)
│                                        영역 = Rect2(0, -2755, 6191.5, 3480)
├─ 앞바닥
│   └ 앞바닥_띠          실내배경.gd  원본영역 = (0, 962, 2135, 113) · 앞에_그리기 true
├─ 창문_방_바깥빛/틀/살  ColorRect ×6  z -30 / -28
├─ 문간어둠_입구         ColorRect     z -8
│
├─ 지형                  Node2D            ★SS2D 전부. 구간 접두어로 구분
│   ├─ 바닥_STAGE1_BRICK_01          (−500 … 6692 · 전 구간 공용 · 끊김 없음)
│   ├─ 천장_STAGE1_BRICK_01
│   ├─ 벽_왼_BRICK_01 / 벽_오른_BRICK_01
│   ├─ [1-1] 벽선반_A~D · SS_WOOD_BOOKSHELF_TOP_01 · SS_WOOD_WARDROBE_TOP_01 · SS_BRICK_SPIKE_BASE_01
│   ├─ [1-2] 벽선반_E~I · SS_WOOD_CURTAIN_L/ROD/R_01 · SS_BRICK_WINSILL_MID_01 · SS_BRICK_WINBAR_01
│   ├─ [1-3] SS_WOOD_BEDHEAD_01 · SS_WOOD_MATTRESS_01 · SS_WOOD_CRATE_01
│   │        SS_WOOD_WARDROBE_BODY_01 · SS_WOOD_BOOKSHELF_BODY_01 · _STEP_01~04
│   │        SS_WOOD_DESK_01 · SS_BRICK_CEIL_LOW_01
│   └─ [1-4] SS_WOOD_SHELF_A/B_01 · SS_WOOD_TABLE_01 · SS_WOOD_BREAK_FLOOR_01
│
├─ 기믹                  Node2D            ★움직이는 것 · 플레이어에 개입하는 것
│   ├─ 서랍_A            움직이는발판.tscn
│   ├─ 서랍_B            움직이는발판.tscn
│   ├─ 빛밀어냄_창       Area2D + 빛_밀어냄.gd      (신규)
│   ├─ 바람_창틈         Area2D + 바람지대.gd        (신규)
│   ├─ 연필공장_책상     Node2D + 굴러오는연필.gd    (신규)
│   └─ 도약대_매트리스   도약대.tscn
│
├─ 위험물                Node2D            ★닿으면 죽는 것 (group "hazard")
│   └─ 가시_1_1          가시.tscn
│
├─ 장식                  Node2D            (창문 프리팹 등 · 콜리전 없음)
├─ 조명                  Node2D
│   ├─ 창빛_기둥         빛기둥.gd 모드=연출 · 구멍_그리기 false
│   ├─ 빛_창문안쪽       발광체.gd · 알갱이_보이기 false
│   └─ 빛_바닥웅덩이     발광체.gd
├─ 카메라공간            Node2D
│   ├─ 카메라_1_1_등반   1.15
│   ├─ 카메라_1_2_창가   0.85
│   ├─ 카메라_1_3_가구밑 1.10
│   └─ 카메라_1_4_침대   0.95
├─ 입구통로              연결통로.gd (역할=입구)
├─ 출구통로              연결통로.gd (역할=출구 · 다음_씬 = "")
└─ Player                Player.tscn 인스턴스 (튜닝 오버라이드)
```

### 왜 SubScene 으로 안 쪼개나 (도형님 §11 "각 구간을 독립 SubScene 으로")

⚠ **이 프로젝트에서는 그렇게 하면 안 된다.** 이유:

1. `PackedScene.pack()` 은 **owner 가 패킹 루트인 노드의 값만 저장한다.**
   구간을 서브씬으로 만들어 인스턴스하면 빌더가 꽂은 SS2D 점 배열·콜리전 폴리곤이
   **통째로 버려지고 Template 기본 사각형만 남는다.** (v4 빌더 `_색구역()` 주석에 같은 사고 기록)
2. `지형.gd::_ready()` 가 `_meshes.clear()` 로 Template 메시를 비우는 것은
   **인스턴스가 저장 씬에 실린 메시를 물려받는 버그**를 막기 위해서다.
   서브씬을 한 겹 더 끼우면 그 경로가 하나 더 늘어난다.
3. 대신 **접두어 규칙**(`[구간] 이름`)과 **`Node2D` 그룹 노드**로 나눈다.
   에디터에서 접었다 폈다 하면 서브씬과 실용적으로 같다.

**대신 이렇게 독립 테스트한다:** 빌더에 `-- --구간 1_1` 인자를 넣어 **그 구간만 짓는** 모드를 둔다.
(§STEP 10 의 2 단계)

---

# STEP 9 — Gimmick Architecture

## 9.1 신규 스크립트 3 개 · 재사용 4 개

| # | 기믹 | 파일 | 신규? | 줄 수 | 노드 | Layer/Mask | 핵심 Export |
|---|---|---|---|---|---|---|---|
| A | 움직이는 서랍 | `scripts/장애물/움직이는발판.gd` | **재사용** | — | AnimatableBody2D | 1 / 0 | 이동거리 150 · 왕복시간 4.0 |
| B | 가시 | `scripts/장애물/가시.gd` | **재사용** | — | Area2D | 0 / 1 | 칸수 4 · 방향 위 |
| C | 빛 넉백 | `scripts/스마트월드/빛_밀어냄.gd` | **신규** | ~55 | Area2D | 0 / 1 | 광원_위치 · 세기 260 · 수직_비율 0.35 · 공중_배수 1.6 |
| D | 창틈 바람 | `scripts/스마트월드/바람지대.gd` | **신규** | ~45 | Area2D | 0 / 1 | 뜨는힘 900 · 최대_하강속도 220 |
| E | 굴러오는 연필 | `scripts/스마트월드/굴러오는연필.gd` + `연필.tscn` | **신규** | ~60 | Node2D + RigidBody2D | 1/1 · 판정 0/1 | 주기 3.2 · 최대_개수 4 · 수명 9 · 즉사 false |
| F | 트램폴린 | `scripts/스마트월드/도약대.gd` | **재사용** | — | Area2D + StaticBody2D | 0/1 · 발판 1/0 | 도약속도 −1450 · 폭 400 |
| G | 부서지는 바닥 | `scripts/스마트월드/부서지는지형.gd` | **신규** | ~50 | `extends 스마트지형` | 1 / 0 | 필요_명중 3 · 부서짐_지연 0.25 |

**공통 Base Script 는 만들지 않는다.** (도형님 §12 "작은 프로젝트에 과도한 Architecture 금지")
C·D·E 가 `플레이어_밀기()` 를 공유할 만하지만 세 곳 합쳐 8 줄이라 **중복이 더 싸다.**

## 9.2 세 신규 스크립트가 공통으로 지키는 규약

```gdscript
# 이 프로젝트의 Area2D 기믹 문법 (도약대.gd·빛기둥.gd·색레이저.gd 가 전부 이 모양이다)
func _ready() -> void:
    _재구성()
    if Engine.is_editor_hint(): return   # @tool 이라 에디터에서도 도는데, 로직은 런타임만
    add_to_group("<기믹이름>")
    collision_layer = 0                   # ★아무도 나를 감지할 필요가 없다
    collision_mask = 1                    # ★플레이어(레이어 1)만 본다
    monitoring = true
    set_physics_process(true)

func _physics_process(delta: float) -> void:
    for 몸 in get_overlapping_bodies():
        var p := 몸 as CharacterBody2D
        if p == null or not p.is_in_group("player"): continue
        ...
```

### ★ 플레이어에 개입하는 방법 — 절대 헷갈리지 말 것

| 방향 | 방법 | 되는가 | 이유 |
|---|---|---|---|
| **수직** | `p.velocity.y = ...` / `+= ...` | ✅ | `player.gd` 는 y 를 덮어쓰지 않는다 (중력만 누적) |
| **수평** | `p.velocity.x = ...` | ❌ | **다음 프레임에 `dir * move_speed` 로 덮어써진다** |
| **수평** | `p.move_and_collide(Vector2(dx, 0))` | ✅ | velocity 를 안 건드린다. 벽에 부딪히면 알아서 멈춘다 |
| 수평 | `p.global_position.x += dx` | ⚠ 피한다 | 벽을 뚫는다 (`송풍기.gd` 가 연기에만 이 방식을 쓰는 이유) |

**→ `player.gd` 는 한 줄도 안 고친다.**

## 9.3 Signal

이 프로젝트의 기믹들은 **시그널을 거의 쓰지 않는다** (`페인트코어.상태_변경` 하나뿐).
새 기믹도 시그널을 만들지 않는다 — 스테이지에 매니저가 없고, 각자 `_physics_process` 에서
자기 일만 한다. **필요해지면 그때 만든다.**
예외: `부서지는지형.부서짐()` 하나 — 1층 낙하 연출(카메라 트라우마·소리)을 붙일 자리다.

---

# STEP 10 — Implementation Order

각 단계마다 **먼저 무엇을 검증하는지**를 같이 적었다.
⚠ AGENTS.md §4 — `build_*.gd` 는 **평소에 돌리지 않는다.** 아래 순서는 "이번 제작" 한정이다.
⚠ 메모리 교훈 — **단계마다 커밋한다.** (2026-08-30 에 외부 `git reset --hard` 로 392 파일이 날아간 적 있다)

## 0. 착수 전 (코드 0 줄)

```bash
git fetch && git status
Godot --headless --path . -s res://tools/원화_잘라보기.gd -- res://assets/background/room.png C:/tmp/책장.png 240 260 240 600 3
```
- **검증:** §3.2 표의 `≈` 붙은 세로 좌표 6 개를 ±10 px 안으로 확정한다.
- **결정 필요:** §1.11 (A) `월드.gd` 4 줄 추가 — **도형님 승인**

## 1. 배율 · 배경만 (지형 0 개)

`tools/build_스테이지_1_2층방.gd` 를 v5 로 고친다. **이 단계에서는 배경 + 바닥 + 벽 + 천장만.**
```bash
Godot --headless --path . -s res://tools/build_스테이지_1_2층방.gd
Godot --path . -s res://tools/스크린샷.gd -- res://scenes/집/스테이지_1_2층방.tscn
```
- **검증 ①** 배경이 한 장으로 이어져 보이는가 (이음매·반전 없음)
- **검증 ②** `원화_밝기 1.05` 에서 화면이 회색으로 뜨지 않는가 ← v3 이 여기서 두 번 틀렸다
- **검증 ③** 카메라 줌 1.00 에서 방이 "쥐가 돌아다니는" 크기로 보이는가 ← **도형님 눈으로 확인**
- ⚠ `스크린샷.gd` 에 `--headless` 를 붙이면 안 된다

## 2. 구간 1-1 지형만

빌더에 `--구간` 인자를 추가하고 1-1 만 짓는다.
```bash
Godot --headless --path . -s res://tools/진단_지형메시.gd -- res://scenes/집/스테이지_1_2층방.tscn
Godot --headless --path . -s res://tools/진단_콜리전대_그림.gd -- res://scenes/집/스테이지_1_2층방.tscn
Godot --headless --path . -s res://tools/레벨검사.gd -- res://scenes/집/스테이지_1_2층방.tscn
```
- **검증 ①** `진단_지형메시` 의 **"메시" 열이 전부 2** 인가 (1 이면 자기관통 → 규칙 7)
- **검증 ②** `진단_콜리전대_그림` 이 전부 **0.0 px** 인가
- **검증 ③** `레벨검사` **도달불가 0 · 소프트락 0**
  → §4.2 의 규칙 3 겹침(벽선반 C vs 책장)이 여기서 잡힌다. 해결안 ①/② 중 하나를 고른다.

## 3. 구간 1-3 지형 (1-2 보다 먼저)

★ 1-2 가 아니라 1-3 을 먼저 짓는다. **1-3 은 기믹 없이 지형만으로 성립**하고,
**바닥·낮은 천장·책장 계단이 스테이지 전체의 뼈대**라 여기가 틀리면 나머지가 다 틀어진다.
- **검증:** 위 3 종 + `--지도` 로 단면 확인. 특히 §6.1 의 **낙차 417 / 464 를 2 단으로 쪼갠 결과**

## 4. 구간 1-2 · 1-4 지형

- **검증:** 위 3 종. §5.2 · §7.2 의 규칙 3 검산이 실제로 통과하는지

## 5. 기믹 — 재사용 4 개 먼저 (서랍 · 가시 · 도약대 · 통로)

- **검증 ①** 서랍 위에 선 플레이어가 같이 실려 가는가 (`[확인 필요]` §4.3)
- **검증 ②** 가시가 **실제로 죽이는가** (§1.11 (A) 수정 후)
- **검증 ③** 도약대 상승이 459 px 인가 → 선반 A(−720)에 닿는가
- **검증 ④** 도약대 `발판` 과 매트리스 SS2D 콜리전이 안 겹치는가

## 6. 기믹 — 신규 3 개 (빛 넉백 · 바람 · 연필)

**한 번에 하나씩.** 만들 때마다 §9.2 표의 "수평은 `move_and_collide`" 를 지켰는지 확인.
- **검증 ①** 빛 넉백: 걸어서 거스를 수 있는가 (세기 260 < move_speed 390)
- **검증 ②** 빛 넉백: 같은 자리에 오래 서 있어도 **속도가 누적되지 않는가**
- **검증 ③** 바람: 체공이 0.63 → 약 1.1 초로 늘어 **틈 240** 을 건너는가
- **검증 ④** 연필: 20 초 방치했을 때 **개수가 4 를 안 넘는가** · 프레임이 안 떨어지는가

## 7. 파괴 가능 바닥 + 1층 연결

- **검증 ①** 총 3 발로 부서지는가 (총·총알·페인트코어를 **안 고치고**)
- **검증 ②** 부서진 뒤 `collision_layer = 0` 이 `set_deferred` 로 적용되는가
- **검증 ③** `[확인 필요]` **세로 통로**가 되는가 → 안 되면 착지 발판 + 가로 통로로

## 8. 전체 검사 + 문서

```bash
Godot --headless --path . -s res://tools/레벨검사.gd -- res://scenes/집/스테이지_1_2층방.tscn --지도
Godot --headless --path . -s res://tools/검증_씬로드.gd
Godot --headless --path . -s res://tools/측정_스테이지_플레이타임.gd -- res://scenes/집/스테이지_1_2층방.tscn
```
- **목표 수치:** 도달불가 **0** · 소프트락 **0** · 콜리전대그림 **전부 0.0 px** · 메시 **전부 2 장** · 깨진 참조 **0**
- **알고 넘기는 예외 1 건:** §5.4 의 바람 틈 240 (검사기는 바람을 모른다)
- `docs/작업기록_<날짜>_Claude_STAGE1_v5_4구간.md` 를 남긴다 (CLAUDE.md 규칙 2)

---

# STEP 11 — Stage Flow 분석 (도형님 §14)

| | **1-1 Zigzag Entry** | **1-2 Window Light & Wind** | **1-3 Bookshelf Obstacles** | **1-4 Descent** |
|---|---|---|---|---|
| **목적** | 조작·공간 학습 | 이 게임의 "환경이 나를 밀어낸다" 도입 | 공간의 리듬 · 이동 제한 | 총이라는 동사 학습 + 마무리 |
| **배우는 것** | 걷기·점프·"움직이는 발판을 탄다" | "빛과 바람은 지형처럼 작용한다" | "점프를 못 하는 곳이 있다" | "막힌 길은 쏴서 연다" |
| **난이도** | 2 / 10 | **5 / 10** ← 정점 | 4 / 10 | 3 / 10 |
| **핵심 기믹** | 움직이는 서랍 | **빛 넉백** | **Brick 낮은 천장** | **도약대(트램폴린)** |
| **보조 기믹** | Brick 가시 | 창틈 바람 | 굴러오는 연필 | 부서지는 바닥 |
| **위험 요소** | 가시 1 곳 (즉사) | 낙하 (≤390 · 즉사 없음) | 연필 넉백 (즉사 없음) | 낙하 (매트리스가 받는다) |
| **안전 구간** | 옷장 오른쪽 평지 폭 500 | 빛 밖 벽 선반 −1191 | 책장 중단 선반 −550 | 탁자 위 평지 폭 700 |
| **Checkpoint** | 불필요 | `안전지점_자동저장` 으로 충분 | 〃 | 〃 |
| **다음으로** | 옷장 끝 → 벽 선반 (같은 높이) | 벽 선반 −1191 → 왼쪽으로 (같은 높이) | 궤짝 → 바닥 (같은 높이) | 바닥 파괴 → **낙하 → STAGE 2** |

## 연결이 자연스러운가 — 세 가지 장치

1. **높이가 이어진다.** 구간 경계는 전부 **같은 높이의 평지**다. 계단을 오르내리며
   구간이 바뀌지 않는다 → "여기서부터 다른 스테이지" 라는 이음매가 안 느껴진다.
2. **카메라 줌이 바뀐다.** 1.15 → 0.85 → 1.10 → 0.95. 공간이 좁아졌다 넓어졌다 한다.
3. **왔던 곳이 보인다.** 1-3 의 바닥에서 위를 보면 1-1 에서 밟았던 옷장 윗면이 보이고,
   1-4 의 매트리스는 1-3 에서 이미 한 번 밟고 지나간 곳이다.
   **한 방 안이라서 생기는 효과** — 구역을 벽으로 끊은 v4 로는 절대 안 되던 것이다.

---

## 부록 A — "확인 필요" 목록 (추측으로 채우지 않은 것)

| # | 항목 | 어디 | 확인 방법 |
|---|---|---|---|
| 1 | 가구 6 종의 **세로** 원화 좌표 (±35 px) | §3.2 | `tools/원화_잘라보기.gd` 확대 |
| 2 | `움직이는발판` 위에 선 플레이어가 실려 가는가 | §4.3 | 실행 후 눈으로 |
| 3 | `연결통로` 가 **세로(아래) 방향**을 지원하는가 | §7.5 | 코드 확인 + 실행 |
| 4 | 도약대 `발판` 과 매트리스 SS2D 콜리전 겹침 | §7.4 | `진단_콜리전대_그림` |
| 5 | 1-3 의 낙차 417 / 464 를 몇 단으로 쪼갤지 | §6.1 | `레벨검사` |
| 6 | §4.2 규칙 3 겹침 해결안 ① vs ② | §4.2 | `레벨검사` |
| 7 | 연필 `즉사` 를 켤지 말지 | §6.3 | 도형님 판단 |

## 부록 B — 절대 손대지 않는 것 (도형님 §2 · §13)

`player.gd` · `gun.gd` · `bullet.gd` · `총.gd` · `총알.gd` · `페인트_코어.gd` ·
`지형.gd`(상속만 한다) · SS2D Template 12 종 · `assets/textures/smartshape/**` 의 `.tres` 재질 ·
`terrain_tileset.tres` · `proto_camera.gd` · `챕터.gd` 의 스테이지표 · 기존 정상 작동 씬

**유일한 예외 요청**: `월드.gd::_사망_판정()` 에 hazard 그룹 4 줄 (§1.11 A) — **승인 대기.**
